language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t jyong9591/react-test-app -f ./frontend/dockerfile.dev ./frontend

script:
  - docker run -e CI=true jyong9591/react-test-app npm run test

after_success:
  - docker build -t jyong9591/multi-frontend ./frontend
  - docker build -t jyong9591/multi-backend ./backend
  - docker build -t jyong9591/multi-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push jyong9591/multi-frontend
  - docker push jyong9591/multi-backend
  - docker push jyong9591/multi-nginx
